---
bgm: false
screen:
  width: 1024
  height: 768
i18n:
  locale: zh-CN
ygocore:
  announcements:
  - !ruby/object:Announcement
    title: Mycard 服务进入不稳定期
    url: http://blog.my-card.in/mycard-%E6%9C%8D%E5%8A%A1%E8%BF%9B%E5%85%A5%E4%B8%8D%E7%A8%B3%E5%AE%9A%E6%9C%9F/
    time: 2013-07-24
  - !ruby/object:Announcement
    title: SD25已更新，戳我查看新卡列表
    url: https://goo.gl/j3V3R
    time: 2013-06-16
  - !ruby/object:Announcement
    title: 和我签下契约，成为魔法少女吧 (Mycard团队成员招募) <-戳我
    url: https://my-card.in/humans
    time: 2013-04-13
  - !ruby/object:Announcement
    title: mycard可以使用Google账号登录了<-戳我查看详情
    url: https://github.com/mycard/mycard/wiki/%E7%94%A8%E6%88%B7
    time: 2013-03-25
  - !ruby/object:Announcement
    title: 可以使用手机登录聊天室了 <-戳我查看详情
    url: https://github.com/mycard/mycard/wiki/聊天室
    time: 2013-03-09
  - !ruby/object:Announcement
    title: 网页大厅测试中,需要本机安装了mycard才能用哦
    url: http://my-card.in/rooms/
    time: 2013-02-19
  - !ruby/object:Announcement
    title: ! 'QQ群: MyCard - 萌卡(225669895)'
    url: http://qun.qzone.qq.com/group#!/225669895/home
    time: 2013-02-19
  username: 不如归去
  password: '139578'
game: ygocore
